CREATE TABLE `BITACORA`.`LOG_GENERAL_AT` (
  `id_LOG_GENERAL_AT` INT NOT NULL,
  `nombre_api` VARCHAR(45) NULL,
  `respuesta` VARCHAR(300) NULL,
  `respuesta_error` VARCHAR(300) NULL,
  `fecha_control_interno` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_LOG_GENERAL_AT`));
